services:
  redis:
    image: redis:latest
    container_name: simple_offer_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  bot:
    build: .
    container_name: simple_offer_bot
    restart: always
    depends_on:
      - redis
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    volumes:
      - .:/app
      - ./data:/app/data
